
 platform :ios, '9.0'


target 'HHWeChatDylib' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for HHWeChatDylib
pod 'FLEX'

end
